import { createContext, useContext, useEffect, useState } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation object
const translations: Record<Language, Record<string, string>> = {
  ar: {
    // Navigation
    'dashboard': 'لوحة التحكم',
    'data_collection': 'جمع البيانات',
    'leads': 'العملاء المحتملين',
    'contacts': 'جهات الاتصال',
    'companies': 'الشركات',
    'calls': 'المكالمات',
    'analytics': 'التحليلات',
    'settings': 'الإعدادات',
    'notifications': 'الإشعارات',
    
    // Common
    'search': 'بحث...',
    'add': 'إضافة',
    'edit': 'تعديل',
    'delete': 'حذف',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'close': 'إغلاق',
    'submit': 'إرسال',
    'loading': 'جاري التحميل...',
    'error': 'خطأ',
    'success': 'نجح',
    'warning': 'تحذير',
    'info': 'معلومات',
    'confirm': 'تأكيد',
    'yes': 'نعم',
    'no': 'لا',
    'all': 'الكل',
    'filter': 'تصفية',
    'export': 'تصدير',
    'import': 'استيراد',
    'refresh': 'تحديث',
    'more': 'المزيد',
    'actions': 'الإجراءات',
    'view': 'عرض',
    'download': 'تحميل',
    'upload': 'رفع',
    
    // Dashboard
    'welcome': 'مرحباً',
    'overview': 'نظرة عامة',
    'recent_activity': 'النشاط الأخير',
    'statistics': 'الإحصائيات',
    'total_leads': 'إجمالي العملاء المحتملين',
    'active_calls': 'المكالمات النشطة',
    'conversion_rate': 'معدل التحويل',
    'revenue': 'الإيرادات',
    
    // Leads
    'add_lead': 'إضافة عميل محتمل',
    'lead_name': 'اسم العميل المحتمل',
    'lead_status': 'حالة العميل المحتمل',
    'lead_source': 'مصدر العميل المحتمل',
    'lead_score': 'نقاط العميل المحتمل',
    'lead_details': 'تفاصيل العميل المحتمل',
    'assign_to': 'تعيين إلى',
    'new': 'جديد',
    'contacted': 'تم الاتصال',
    'qualified': 'مؤهل',
    'proposal': 'عرض',
    'negotiation': 'تفاوض',
    'won': 'فوز',
    'lost': 'خسارة',
    
    // Calls
    'make_call': 'إجراء مكالمة',
    'call_duration': 'مدة المكالمة',
    'call_status': 'حالة المكالمة',
    'call_notes': 'ملاحظات المكالمة',
    'call_queue': 'قائمة المكالمات',
    'auto_dial': 'الاتصال التلقائي',
    'answered': 'تم الرد',
    'busy': 'مشغول',
    'no_answer': 'لا رد',
    'voicemail': 'بريد صوتي',
    
    // Settings
    'profile': 'الملف الشخصي',
    'account': 'الحساب',
    'preferences': 'التفضيلات',
    'security': 'الأمان',
    'integrations': 'التكامل',
    'theme': 'المظهر',
    'language': 'اللغة',
    'light_mode': 'وضع النهار',
    'dark_mode': 'وضع الليل',
    'arabic': 'العربية',
    'english': 'الإنجليزية',
    
    // User
    'sign_in': 'تسجيل الدخول',
    'sign_out': 'تسجيل الخروج',
    'sign_up': 'إنشاء حساب',
    'username': 'اسم المستخدم',
    'password': 'كلمة المرور',
    'email': 'البريد الإلكتروني',
    'phone': 'الهاتف',
    'role': 'الدور',
    'admin': 'مدير',
    'manager': 'مشرف',
    'sales': 'مبيعات',
    
    // Company
    'company_name': 'اسم الشركة',
    'company_size': 'حجم الشركة',
    'industry': 'الصناعة',
    'website': 'الموقع الإلكتروني',
    'address': 'العنوان',
    
    // Analytics
    'performance': 'الأداء',
    'reports': 'التقارير',
    'charts': 'الرسوم البيانية',
    'trends': 'الاتجاهات',
    'comparison': 'المقارنة',
    'period': 'الفترة',
    'daily': 'يومي',
    'weekly': 'أسبوعي',
    'monthly': 'شهري',
    'yearly': 'سنوي',
    
    // Notifications
    'mark_as_read': 'وضع علامة كمقروء',
    'mark_all_read': 'وضع علامة على الكل كمقروء',
    'no_notifications': 'لا توجد إشعارات',
    
    // Messages
    'message_sent': 'تم إرسال الرسالة',
    'message_failed': 'فشل إرسال الرسالة',
    'changes_saved': 'تم حفظ التغييرات',
    'changes_failed': 'فشل حفظ التغييرات',
    'delete_confirm': 'هل أنت متأكد من الحذف؟',
    'no_data': 'لا توجد بيانات',
    
    // Additional
    'calendar': 'التقويم',
    'templates': 'القوالب',
    'users': 'المستخدمون',
    'employee_performance': 'أداء الموظفين',
    'potential_customers': 'العملاء المحتملين',
    'manage_customer_base': 'إدارة قاعدة العملاء',
    'export_csv': 'تصدير CSV',
    'add_customer': 'إضافة عميل',
    'status': 'الحالة',
    'state': 'الحالة',
    'need_follow_up': 'يحتاج متابعة',
    'meeting_scheduled': 'اجتماع',
    'disabled': 'معطلة',
    'rejected': 'مرفوض',
    'company': 'الشركة',
    'city': 'المدينة',
    'assigned_to': 'مسند إلى',
    'source': 'المصدر',
    'view_details': 'عرض التفاصيل',
    'call': 'اتصال',
    'followup': 'متابعة',
    'meeting': 'اجتماع',
    'closed': 'مغلق',
    'recent': 'حديث',
    'import_from': 'استيراد من',
    'auto_dial_feature': 'الاتصال التلقائي',
    'schedule': 'جدولة',
    'user_management': 'إدارة المستخدمين',
    
    // CallsPage translations
    'calls_log': 'سجل المكالمات',
    'all_recorded_calls': 'جميع المكالمات المسجلة',
    'total_calls': 'إجمالي المكالمات',
    'successful_calls': 'مكالمات ناجحة',
    'contact_rate': 'معدل التواصل',
    'average_duration': 'متوسط المدة',
    'result': 'النتيجة',
    'duration': 'المدة',
    'notes': 'الملاحظات',
    'next_followup': 'المتابعة القادمة',
    'date_time': 'التاريخ والوقت',
    'employee': 'الموظف',
    'call_answered': 'رد على المكالمة',
    'seconds': 'ث',
    
    // AutoDialPage translations
    'auto_dial_queue': 'قائمة الاتصال التلقائي',
    'manage_auto_calls': 'إدارة وتنظيم المكالمات التلقائية',
    'start_dialing': 'بدء الاتصال',
    'pause': 'إيقاف مؤقت',
    'skip': 'تخطي',
    'in_queue': 'في قائمة الانتظار',
    'potential_client': 'عميل محتمل',
    'called': 'تم الاتصال',
    'call_completed': 'مكالمة مكتملة',
    'remaining': 'متبقي',
    'call_word': 'مكالمة',
    'state_status': 'الحالة',
    'active': 'نشط',
    'stopped': 'متوقف',
    'calling_now': 'جاري الاتصال...',
    'waiting_mode': 'في وضع الانتظار',
    'progress': 'التقدم',
    'add_to_queue': 'إضافة إلى قائمة الاتصال',
    'select_lead': 'اختر عميل محتمل',
    'call_list': 'قائمة المكالمات',
    'queue_empty': 'قائمة الاتصال فارغة',
    'add_leads_to_start': 'قم بإضافة عملاء محتملين للبدء',
    'assigned_to_label': 'مسند إلى',
    'not_specified': 'غير محدد',
    'calling_status': 'جاري الاتصال',
    'was_called': 'تم الاتصال',
    
    // ImportCSVPage translations
    'import_leads': 'استيراد العملاء المحتملين',
    'import_from_csv': 'استيراد بيانات العملاء من ملفات CSV',
    'download_template': 'تحميل قالب CSV',
    'import_instructions': 'تعليمات الاستيراد',
    'required_columns': 'الأعمدة المطلوبة',
    'required_columns_desc': 'company_name, phone, industry, city',
    'optional_columns': 'الأعمدة الاختيارية',
    'optional_columns_desc': 'email, website, source',
    'notes_title': 'ملاحظات',
    'phone_format_note': 'رقم الهاتف يجب أن يبدأ بـ 0 ويكون 10-11 رقم',
    'ignore_numbers_note': 'سيتم تجاهل الأرقام المكررة تلقائياً',
    'field_validation_note': 'يجب تحديد مصدر البيانات وموظف المبيعات قبل الاستيراد',
    'import_setup': 'إعدادات الاستيراد',
    'data_source': 'مصدر البيانات',
    'responsible_employee': 'موظف المبيعات المسؤول',
    'select_employee': 'اختر موظف',
    'csv_upload': 'رفع ملف CSV',
    'upload_csv_file': 'قم برفع ملف CSV',
    'drag_drop': 'اسحب وأفلت الملف هنا أو',
    'browse': 'تصفح',
    'upload_status': 'حالة الرفع',
    'file_selected': 'تم اختيار الملف',
    'rows_loaded': 'صف محمل',
    'view_preview': 'عرض المعاينة',
    'remove_file': 'إزالة الملف',
    'import_preview': 'معاين�� الاتيراد',
    'showing_rows': 'عرض أول 10 صفوف',
    'start_import': 'بدء الاستيراد',
    'import_progress': 'تقدم الاستيراد',
    'processing_data': 'جاري معالجة البيانات...',
    'import_results': 'نتائج الاستيراد',
    'total_rows': 'إجمالي الصفوف',
    'imported_successfully': 'تم الاستيراد بنجاح',
    'failed_rows': 'صفوف فاشلة',
    'duplicate_rows': 'صفوف مكررة',
    'new_import': 'استيراد جديد',
    
    // ActivityTimelinePage translations
    'activity_timeline': 'سجل الأنشطة',
    'all_system_activities': 'جميع أنشطة النظام',
    'activity_type': 'نوع النشاط',
    'all_activities': 'كل الأنشطة',
    'calls_only': 'المكالمات فقط',
    'leads_only': 'العملاء فقط',
    'meetings_only': 'الاجتماعات فقط',
    'emails_only': 'البريد الإلكتروني فقط',
    'today': 'اليوم',
    'this_week': 'هذا الأسبوع',
    'this_month': 'هذا الشهر',
    'ago': 'منذ',
    
    // TemplatesPage translations
    'message_templates': 'قوالب الرسائل',
    'manage_message_templates': 'إدارة قوالب الرسائل المحفوظة',
    'create_template': 'إنشاء قالب',
    'template_name': 'اسم القالب',
    'template_category': 'الفئة',
    'template_content': 'المحتوى',
    'variables': 'المتغيرات المتاحة',
    'greeting': 'تحية',
    'followup_template': 'متابعة',
    'proposal_template': 'عرض',
    'thanks': 'شكر',
    'use_template': 'استخدام القالب',
    
    // CalendarPage translations
    'calendar_followups': 'التقويم والمتابعات',
    'scheduled_meetings_followups': 'الاجتماعات والمتابعات المجدولة',
    'add_event': 'إضافة حدث',
    'event_title': 'عنوان الحدث',
    'event_type': 'نوع الحدث',
    'event_date': 'التاريخ',
    'event_time': 'الوقت',
    'event_notes_label': 'ملاحظات',
    'upcoming_events': 'الأحداث القادمة',
    'no_events': 'لا توجد أحداث مجدولة',
    
    // ReportsPage translations
    'reports_analytics': 'التقارير والتحليلات',
    'detailed_reports': 'تقارير مفصلة للأداء',
    'generate_report': 'إنشاء تقرير',
    'report_type': 'نوع التقرير',
    'sales_report': 'تقرير المبيعات',
    'calls_report': 'تقرير المكالمات',
    'leads_report': 'تقرير العملاء',
    'team_report': 'تقرير الفريق',
    'date_range': 'النطاق الزمني',
    'from_date': 'من تاريخ',
    'to_date': 'إلى تاريخ',
    'export_pdf': 'تصدير PDF',
    'export_excel': 'تصدير Excel',
    
    // AnalyticsPage translations
    'advanced_analytics': 'التحليلات المتقدمة',
    'detailed_analytics_insights': 'تحليلات ورؤى تفصيلية',
    'key_metrics': 'المؤشرات الرئيسية',
    'performance_trends': 'اتجاهات الأداء',
    'conversion_funnel': 'قمع التحويل',
    'team_performance': 'أداء الفريق',
    
    // SettingsPage translations
    'system_settings': 'إعدادات النظام',
    'configure_system': 'تكوين إعدادات النظام',
    'general_settings': 'الإعدادات العامة',
    'notification_settings': 'إعدادات الإشعارات',
    'appearance': 'المظهر',
    'system_info': 'معلومات النظام',
    'save_settings': 'حفظ الإعدادات',
    'reset_defaults': 'استعادة الافتراضيات',
    
    // UsersPage translations
    'user_management_title': 'إدارة المستخدمين',
    'manage_system_users': 'إدارة مستخدمي النظام',
    'add_user': 'إضافة مستخدم',
    'full_name': 'الاسم الكامل',
    'user_role': 'الدور',
    'active_status': 'نشط',
    'inactive': 'غير نشط',
    'last_login': 'آخر تسجيل دخول',
    'edit_user': 'تعديل المستخدم',
    'delete_user': 'حذف المستخدم',
    'confirm_password': 'تأكيد كلمة المرور',
    'change_password': 'تغيير كلمة المرور',
    'new_password': 'كلمة مرور جديدة',
    'permissions': 'الصلاحيات',
    'account_active': 'الحساب مفعل',
    'account_inactive': 'الحساب معطل',
    'perm_leads': 'العملاء المحتملون',
    'perm_calls': 'المكالمات',
    'perm_reports': 'التقارير',
    'perm_analytics': 'التحليلات',
    'perm_settings': 'الإعدادات',
    'perm_users': 'إدارة المستخدمين',
    'perm_import': 'الاستيراد',
    'perm_auto_dial': 'الاتصال التلقائي',
    'perm_calendar': 'التقويم',
    'perm_templates': 'القوالب',
    'perm_data_collection': 'جمع البيانات',
    'login_credentials': 'بيانات الدخول',
    'leave_empty_keep_password': 'اتركها فارغة للإبقاء على كلمة المرور الحالية',
    'password_min_6': 'كلمة المرور يجب أن تكون 6 أحرف على الأقل',
    'passwords_not_match': 'كلمتا المرور غير متطابقتين',
    'total_users': 'إجمالي المستخدمين',
    'sales_staff': 'موظفي المبيعات',
    'managers_admins': 'المديرين',
    'active_users': 'المستخدمين النشطين',
    'inactive_users': 'المستخدمين المعطلين',
    // Pipeline
    'pipeline': 'مسار المبيعات',
    'sales_pipeline': 'مسار المبيعات',
    'manage_pipeline': 'إدارة ومتابعة حالات العملاء',
    'move_to': 'نقل إلى',
    'drag_drop_hint': 'اسحب العملاء بين الأعمدة لتغيير حالتهم',
    'no_leads_in_stage': 'لا يوجد عملاء في هذه المرحلة',
    'call_from_phone': 'اتصل من هاتفك',
    'log_call_result': 'تسجيل نتيجة المكالمة',
    'pipeline_new': 'جديد',
    'pipeline_contacted': 'تم التواصل',
    'pipeline_followup': 'متابعة',
    'pipeline_meeting': 'اجتماع',
    'pipeline_closed': 'مغلق',
    'pipeline_lost': 'خسارة',
  },
  en: {
    // Navigation
    'dashboard': 'Dashboard',
    'data_collection': 'Data Collection',
    'leads': 'Leads',
    'contacts': 'Contacts',
    'companies': 'Companies',
    'calls': 'Calls',
    'analytics': 'Analytics',
    'settings': 'Settings',
    'notifications': 'Notifications',
    
    // Common
    'search': 'Search...',
    'add': 'Add',
    'edit': 'Edit',
    'delete': 'Delete',
    'save': 'Save',
    'cancel': 'Cancel',
    'close': 'Close',
    'submit': 'Submit',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',
    'warning': 'Warning',
    'info': 'Info',
    'confirm': 'Confirm',
    'yes': 'Yes',
    'no': 'No',
    'all': 'All',
    'filter': 'Filter',
    'export': 'Export',
    'import': 'Import',
    'refresh': 'Refresh',
    'more': 'More',
    'actions': 'Actions',
    'view': 'View',
    'download': 'Download',
    'upload': 'Upload',
    
    // Dashboard
    'welcome': 'Welcome',
    'overview': 'Overview',
    'recent_activity': 'Recent Activity',
    'statistics': 'Statistics',
    'total_leads': 'Total Leads',
    'active_calls': 'Active Calls',
    'conversion_rate': 'Conversion Rate',
    'revenue': 'Revenue',
    
    // Leads
    'add_lead': 'Add Lead',
    'lead_name': 'Lead Name',
    'lead_status': 'Lead Status',
    'lead_source': 'Lead Source',
    'lead_score': 'Lead Score',
    'lead_details': 'Lead Details',
    'assign_to': 'Assign To',
    'new': 'New',
    'contacted': 'Contacted',
    'qualified': 'Qualified',
    'proposal': 'Proposal',
    'negotiation': 'Negotiation',
    'won': 'Won',
    'lost': 'Lost',
    
    // Calls
    'make_call': 'Make Call',
    'call_duration': 'Call Duration',
    'call_status': 'Call Status',
    'call_notes': 'Call Notes',
    'call_queue': 'Call Queue',
    'auto_dial': 'Auto Dial',
    'answered': 'Answered',
    'busy': 'Busy',
    'no_answer': 'No Answer',
    'voicemail': 'Voicemail',
    
    // Settings
    'profile': 'Profile',
    'account': 'Account',
    'preferences': 'Preferences',
    'security': 'Security',
    'integrations': 'Integrations',
    'theme': 'Theme',
    'language': 'Language',
    'light_mode': 'Light Mode',
    'dark_mode': 'Dark Mode',
    'arabic': 'Arabic',
    'english': 'English',
    
    // User
    'sign_in': 'Sign In',
    'sign_out': 'Sign Out',
    'sign_up': 'Sign Up',
    'username': 'Username',
    'password': 'Password',
    'email': 'Email',
    'phone': 'Phone',
    'role': 'Role',
    'admin': 'Admin',
    'manager': 'Manager',
    'sales': 'Sales',
    
    // Company
    'company_name': 'Company Name',
    'company_size': 'Company Size',
    'industry': 'Industry',
    'website': 'Website',
    'address': 'Address',
    
    // Analytics
    'performance': 'Performance',
    'reports': 'Reports',
    'charts': 'Charts',
    'trends': 'Trends',
    'comparison': 'Comparison',
    'period': 'Period',
    'daily': 'Daily',
    'weekly': 'Weekly',
    'monthly': 'Monthly',
    'yearly': 'Yearly',
    
    // Notifications
    'mark_as_read': 'Mark as Read',
    'mark_all_read': 'Mark All as Read',
    'no_notifications': 'No Notifications',
    
    // Messages
    'message_sent': 'Message Sent',
    'message_failed': 'Message Failed',
    'changes_saved': 'Changes Saved',
    'changes_failed': 'Changes Failed',
    'delete_confirm': 'Are you sure you want to delete?',
    'no_data': 'No Data',
    
    // Additional
    'calendar': 'Calendar',
    'templates': 'Templates',
    'users': 'Users',
    'employee_performance': 'Employee Performance',
    'potential_customers': 'Potential Customers',
    'manage_customer_base': 'Manage Customer Base',
    'export_csv': 'Export CSV',
    'add_customer': 'Add Customer',
    'status': 'Status',
    'state': 'State',
    'need_follow_up': 'Need Follow Up',
    'meeting_scheduled': 'Meeting Scheduled',
    'disabled': 'Disabled',
    'rejected': 'Rejected',
    'company': 'Company',
    'city': 'City',
    'assigned_to': 'Assigned To',
    'source': 'Source',
    'view_details': 'View Details',
    'call': 'Call',
    'followup': 'Follow Up',
    'meeting': 'Meeting',
    'closed': 'Closed',
    'recent': 'Recent',
    'import_from': 'Import From',
    'auto_dial_feature': 'Auto Dial Feature',
    'schedule': 'Schedule',
    'user_management': 'User Management',
    
    // CallsPage translations
    'calls_log': 'Calls Log',
    'all_recorded_calls': 'All Recorded Calls',
    'total_calls': 'Total Calls',
    'successful_calls': 'Successful Calls',
    'contact_rate': 'Contact Rate',
    'average_duration': 'Average Duration',
    'result': 'Result',
    'duration': 'Duration',
    'notes': 'Notes',
    'next_followup': 'Next Follow-up',
    'date_time': 'Date & Time',
    'employee': 'Employee',
    'call_answered': 'Call Answered',
    'seconds': 's',
    
    // AutoDialPage translations
    'auto_dial_queue': 'Auto Dial Queue',
    'manage_auto_calls': 'Manage and organize automatic calls',
    'start_dialing': 'Start Dialing',
    'pause': 'Pause',
    'skip': 'Skip',
    'in_queue': 'In Queue',
    'potential_client': 'Potential Lead',
    'called': 'Called',
    'call_completed': 'Call Completed',
    'remaining': 'Remaining',
    'call_word': 'Call',
    'state_status': 'Status',
    'active': 'Active',
    'stopped': 'Stopped',
    'calling_now': 'Calling now...',
    'waiting_mode': 'In waiting mode',
    'progress': 'Progress',
    'add_to_queue': 'Add to Call Queue',
    'select_lead': 'Select a lead',
    'call_list': 'Call List',
    'queue_empty': 'Call queue is empty',
    'add_leads_to_start': 'Add leads to get started',
    'assigned_to_label': 'Assigned to',
    'not_specified': 'Not specified',
    'calling_status': 'Calling',
    'was_called': 'Called',
    
    // ImportCSVPage translations
    'import_leads': 'Import Leads',
    'import_from_csv': 'Import lead data from CSV files',
    'download_template': 'Download CSV Template',
    'import_instructions': 'Import Instructions',
    'required_columns': 'Required Columns',
    'required_columns_desc': 'company_name, phone, industry, city',
    'optional_columns': 'Optional Columns',
    'optional_columns_desc': 'email, website, source',
    'notes_title': 'Notes',
    'phone_format_note': 'Phone number must start with 0 and be 10-11 digits',
    'ignore_numbers_note': 'Duplicate numbers will be automatically ignored',
    'field_validation_note': 'Data source and sales employee must be specified before import',
    'import_setup': 'Import Setup',
    'data_source': 'Data Source',
    'responsible_employee': 'Responsible Sales Employee',
    'select_employee': 'Select Employee',
    'csv_upload': 'Upload CSV File',
    'upload_csv_file': 'Upload a CSV file',
    'drag_drop': 'Drag and drop file here or',
    'browse': 'Browse',
    'upload_status': 'Upload Status',
    'file_selected': 'File selected',
    'rows_loaded': 'rows loaded',
    'view_preview': 'View Preview',
    'remove_file': 'Remove File',
    'import_preview': 'Import Preview',
    'showing_rows': 'Showing first 10 rows',
    'start_import': 'Start Import',
    'import_progress': 'Import Progress',
    'processing_data': 'Processing data...',
    'import_results': 'Import Results',
    'total_rows': 'Total Rows',
    'imported_successfully': 'Imported Successfully',
    'failed_rows': 'Failed Rows',
    'duplicate_rows': 'Duplicate Rows',
    'new_import': 'New Import',
    
    // ActivityTimelinePage translations
    'activity_timeline': 'Activity Timeline',
    'all_system_activities': 'All System Activities',
    'activity_type': 'Activity Type',
    'all_activities': 'All Activities',
    'calls_only': 'Calls Only',
    'leads_only': 'Leads Only',
    'meetings_only': 'Meetings Only',
    'emails_only': 'Emails Only',
    'today': 'Today',
    'this_week': 'This Week',
    'this_month': 'This Month',
    'ago': 'Ago',
    
    // TemplatesPage translations
    'message_templates': 'Message Templates',
    'manage_message_templates': 'Manage Saved Message Templates',
    'create_template': 'Create Template',
    'template_name': 'Template Name',
    'template_category': 'Category',
    'template_content': 'Content',
    'variables': 'Available Variables',
    'greeting': 'Greeting',
    'followup_template': 'Follow-up',
    'proposal_template': 'Proposal',
    'thanks': 'Thanks',
    'use_template': 'Use Template',
    
    // CalendarPage translations
    'calendar_followups': 'Calendar & Follow-ups',
    'scheduled_meetings_followups': 'Scheduled Meetings & Follow-ups',
    'add_event': 'Add Event',
    'event_title': 'Event Title',
    'event_type': 'Event Type',
    'event_date': 'Date',
    'event_time': 'Time',
    'event_notes_label': 'Notes',
    'upcoming_events': 'Upcoming Events',
    'no_events': 'No Scheduled Events',
    
    // ReportsPage translations
    'reports_analytics': 'Reports & Analytics',
    'detailed_reports': 'Detailed Performance Reports',
    'generate_report': 'Generate Report',
    'report_type': 'Report Type',
    'sales_report': 'Sales Report',
    'calls_report': 'Calls Report',
    'leads_report': 'Leads Report',
    'team_report': 'Team Report',
    'date_range': 'Date Range',
    'from_date': 'From Date',
    'to_date': 'To Date',
    'export_pdf': 'Export PDF',
    'export_excel': 'Export Excel',
    
    // AnalyticsPage translations
    'advanced_analytics': 'Advanced Analytics',
    'detailed_analytics_insights': 'Detailed Analytics Insights',
    'key_metrics': 'Key Metrics',
    'performance_trends': 'Performance Trends',
    'conversion_funnel': 'Conversion Funnel',
    'team_performance': 'Team Performance',
    
    // SettingsPage translations
    'system_settings': 'System Settings',
    'configure_system': 'Configure System Settings',
    'general_settings': 'General Settings',
    'notification_settings': 'Notification Settings',
    'appearance': 'Appearance',
    'system_info': 'System Info',
    'save_settings': 'Save Settings',
    'reset_defaults': 'Reset Defaults',
    
    // UsersPage translations
    'user_management_title': 'User Management',
    'manage_system_users': 'Manage System Users',
    'add_user': 'Add User',
    'full_name': 'Full Name',
    'user_role': 'User Role',
    'active_status': 'Active',
    'inactive': 'Inactive',
    'last_login': 'Last Login',
    'edit_user': 'Edit User',
    'delete_user': 'Delete User',
    'confirm_password': 'Confirm Password',
    'change_password': 'Change Password',
    'new_password': 'New Password',
    'permissions': 'Permissions',
    'account_active': 'Account Active',
    'account_inactive': 'Account Inactive',
    'perm_leads': 'Leads',
    'perm_calls': 'Calls',
    'perm_reports': 'Reports',
    'perm_analytics': 'Analytics',
    'perm_settings': 'Settings',
    'perm_users': 'User Management',
    'perm_import': 'Import',
    'perm_auto_dial': 'Auto Dial',
    'perm_calendar': 'Calendar',
    'perm_templates': 'Templates',
    'perm_data_collection': 'Data Collection',
    'login_credentials': 'Login Credentials',
    'leave_empty_keep_password': 'Leave empty to keep current password',
    'password_min_6': 'Password must be at least 6 characters',
    'passwords_not_match': 'Passwords do not match',
    'total_users': 'Total Users',
    'sales_staff': 'Sales Staff',
    'managers_admins': 'Managers & Admins',
    'active_users': 'Active Users',
    'inactive_users': 'Inactive Users',
    // Pipeline
    'pipeline': 'Pipeline',
    'sales_pipeline': 'Sales Pipeline',
    'manage_pipeline': 'Manage and track lead statuses',
    'move_to': 'Move to',
    'drag_drop_hint': 'Drag leads between columns to change their status',
    'no_leads_in_stage': 'No leads in this stage',
    'call_from_phone': 'Call from your phone',
    'log_call_result': 'Log Call Result',
    'pipeline_new': 'New',
    'pipeline_contacted': 'Contacted',
    'pipeline_followup': 'Follow Up',
    'pipeline_meeting': 'Meeting',
    'pipeline_closed': 'Closed',
    'pipeline_lost': 'Lost',
  }
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('leadengine-language');
    return (saved as Language) || 'ar';
  });

  useEffect(() => {
    const root = document.documentElement;
    root.lang = language;
    root.dir = language === 'ar' ? 'rtl' : 'ltr';
    localStorage.setItem('leadengine-language', language);
  }, [language]);

  const toggleLanguage = () => {
    setLanguageState(prev => prev === 'ar' ? 'en' : 'ar');
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    // During development, HMR might cause temporary context loss
    // Provide a fallback instead of crashing
    console.warn('useLanguage: No LanguageContext found. Using fallback.');
    return {
      language: 'ar' as Language,
      toggleLanguage: () => {},
      setLanguage: () => {},
      t: (key: string) => key,
    };
  }
  return context;
}